name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  artifact_name: app_ver_${{ github.sha }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      app_name: app-${{ matrix.os }}_ver.${{ github.event }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          g++ *.cpp -o ${{ env.app_name }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.app_name }}
          if-no-files-found: warn
  build_win:
    runs-on: windows-2022
    env:
      app_name: app-win22_ver.${{ github.event }}
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - name: build_win
        run: |
          cl /EHsc *.cpp /out:main.exe
          ls
          
      - name: Upload a Build Artifact_win
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.artifact_name }}
          path: main.exe
          if-no-files-found: warn
