name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  artifact_name: app_ver_${{ github.sha }}

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive .
    
    
  build_ubuntu_macos:
    runs-on: ${{ matrix.os }}
    needs: [cpplint]
    env:
      app_name: app-${{ matrix.os }}_ver.${{ github.event }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          g++ *.cpp -o ${{ env.app_name }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.app_name }}
          if-no-files-found: error
          
  build_win:
    runs-on: windows-2022
    needs: [cpplint]
    env:
      app_name: app-win22_ver.${{ github.event }}
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.10.0
      - name: build_win
        run: |
          cl /EHsc *.cpp /Fe: ${{ env.app_name }}
          ls
          
          
      - name: Upload a Build Artifact_win
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.artifact_name }}
          path: "*.exe"
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    needs: [build_ubuntu_macos, build_win]
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v3
    - name: Run Test
      run: ./test.cpp
